language: python
before_install:
  - sudo apt-get install -y libudunits2-dev libxml2
install:
  - pip install tox
script: tox
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=py36-lxml
    - python: 3.7
      env: TOXENV=py37
    - python: 3.7
      env: TOXENV=py37-lxml
    - python: 3.7
      env: TOXENV=quality
    - python: 3.7
      env: TOXENV=docs-html
    - python: 3.7
      env: TOXENV=install
    - python: 3.7
      env: TOXENV=install-lxml
    - python: 3.7
      install:
        - pip install tox coverage
      after_success:
        - codecov
      env: TOXENV=coverage
