language: python
before_install:
  - sudo apt-get install -y libudunits2-dev libxml2
install:
  - pip install tox
script: tox
matrix:
  include:
    - name: run test suite with python 3.6
      python: 3.6
      env: TOXENV=py36
    - name: run test suite with python 3.6 (using lxml)
      python: 3.6
      env: TOXENV=py36-lxml
    - name: run test suite with python 3.7
      python: 3.7
      env: TOXENV=py37
    - name: run test suite with python 3.7 (using lxml)
      python: 3.7
      env: TOXENV=py37-lxml
    - name: typing and style checks
      python: 3.7
      env: TOXENV=checks
    - name: test documentation build
      python: 3.7
      env: TOXENV=docs-html
    - name: test install and import
      python: 3.7
      env: TOXENV=install
    - name: test install and import (using lxml)
      python: 3.7
      env: TOXENV=install-lxml
    - name: generate report for codecov.io
      python: 3.7
      install:
        - pip install tox codecov
      after_success:
        - codecov
      env: TOXENV=coverage
